

CREATE PROC [VH].[GET_DINHNGHIA_PHUONGTIEN]
AS
BEGIN
SELECT * FROM VH.DINHNGHIA_PHUONGTIEN WHERE IS_DELETED=0
END
GO

ALTER PROC [VH].[UPDATE_DINHNGHIA_PHUONGTIEN]
@ID INT = 0, @DONGXE NVARCHAR(50), @HIEUXE NVARCHAR(50), @VT_DONGXE VARCHAR(20), @VT_HIEUXE VARCHAR(20), @IS_DELETED BIT
AS
BEGIN
IF @ID = 0
BEGIN
	INSERT INTO VH.DINHNGHIA_PHUONGTIEN (DONGXE, HIEUXE, VT_DONGXE, VT_HIEUXE, IS_DELETED)
	VALUES (@DONGXE, @HIEUXE, @VT_DONGXE, @VT_HIEUXE, @IS_DELETED)
	SELECT @@IDENTITY
END
ELSE
BEGIN
	UPDATE VH.DINHNGHIA_PHUONGTIEN
	SET DONGXE = @DONGXE, 
		HIEUXE = @HIEUXE,
		VT_DONGXE = @VT_DONGXE,
		VT_HIEUXE = @VT_HIEUXE,
		IS_DELETED = @IS_DELETED
	WHERE ID = @ID
	SELECT @ID
END
END
GO

CREATE PROC [VH].[CREATE_NEW_PHUONGTIEN]
@DINHNGHIA_PT_ID INT, @THANG INT, @NAM INT , @THUTU INT , @CODE VARCHAR(50), @SOCHO INT
AS
BEGIN
	INSERT INTO [VH].[PHUONGTIEN](DINHNGHIA_PT_ID, DOIXE_THANG, DOIXE_NAM, THUTU, CODE, SO_CHO)
	VALUES (@DINHNGHIA_PT_ID, @THANG, @NAM, @THUTU, @CODE, @SOCHO)
	SELECT @@IDENTITY
END 

GO

ALTER PROC [VH].[GET_ALL_PHUONGTIEN]
AS
BEGIN
 SELECT P.ID,
 DP.HIEUXE,
 P.SO_CHO,
 P.NAM_SX,
 P.VUNG_HD_ID,
 P.NGAY_NHAP,
 P.GHICHU_NGAY_NHAP,
 P.NGAY_THANHLY,
 P.GHICHU_NGAY_THANHLY
  FROM [VH].[PHUONGTIEN] P
 JOIN [VH].[DINHNGHIA_PHUONGTIEN] DP ON P.DINHNGHIA_PT_ID = DP.ID 
 WHERE ISNULL(P.IS_DELETED, 0) = 0
END

GO

CREATE PROC [VH].[GET_THONGTIN_PHUONGTIEN_BY_ID]
@ID INT
AS
BEGIN
	SELECT TOP 1 * FROM [VH].[PHUONGTIEN] WHERE ID = @ID
	SELECT TOP 1 * FROM [VH].[GIAYTOXE] WHERE ID_PHUONGTIEN = @ID
	SELECT * FROM [VH].[TRANGTHIETBI] WHERE ID_PHUONGTIEN = @ID

END

GO 

ALTER TABLE [VH].[GIAYTOXE]
ADD BHVC_NOIBO NVARCHAR(200)
GO

ALTER TABLE [VH].[GIAYTOXE]
ADD BHVC_BENNGOAI NVARCHAR(200)

GO

CREATE PROC [VH].[UPDATE_GIAYTOXE]
@ID INT ,
@ID_PT INT, 
@ID_LOAI_CAVET INT,
@TEN_NGAN_HANG NVARCHAR(200),
@NGUOI_PT NVARCHAR(200),
@THOI_HAN_BAN_SAO DATE, 
@BHDS_NGAYHETHAN DATE,
@BHDS_TEN_CTY_BH NVARCHAR(200),
@BHVC_NGAYHETHAN DATE,
@BHVC_TEN_CTY_BH NVARCHAR(200),
@BHVC_NOIBO NVARCHAR(200),
@BHVC_BENNGOAI NVARCHAR(200),
@KIEMDINH_TEMXANH DATE,
@KIEMDINH_TEMVANG DATE,
@PHI_SD_DB DATE,
@SO_THANG_DONG INT,
@THOIHAN_PHUHIEU_HOPDONG DATE,
@GHICHU NTEXT
AS
BEGIN
	IF @ID = 0 
	BEGIN
		INSERT INTO [VH].[GIAYTOXE](ID_PHUONGTIEN, ID_LOAI_CAVET, TEN_NGAN_HANG, NGUOI_PHU_TRACH, THOI_HAN_BAN_SAO, BHDS_NGAYHETHAN, BHDS_TEN_CTY_BH,
									BHVC_NGAYHETHAN, BHVC_TEN_CTY_BH, BHVC_NOIBO, BHVC_BENNGOAI, KIEMDINH_TEMXANH, KIEMDINH_TEMVANG, PHI_SD_DUONGBO_NGAY_HETHAN,
									SO_THANG_DONG, THOIHAN_PHUHIEU_HOPDONG, GHICHU)
		VALUES (@ID_PT, @ID_LOAI_CAVET, @TEN_NGAN_HANG, @NGUOI_PT, @THOI_HAN_BAN_SAO, @BHDS_NGAYHETHAN, @BHDS_TEN_CTY_BH,
				@BHVC_NGAYHETHAN, @BHVC_TEN_CTY_BH, @BHVC_NOIBO, @BHVC_BENNGOAI, @KIEMDINH_TEMXANH, @KIEMDINH_TEMVANG, @PHI_SD_DB, @SO_THANG_DONG, @THOIHAN_PHUHIEU_HOPDONG, @GHICHU)
		SELECT @@IDENTITY
	
	END
	ELSE
		BEGIN
		UPDATE [VH].[GIAYTOXE]
   SET 
      [ID_LOAI_CAVET] = @ID_LOAI_CAVET
      ,[TEN_NGAN_HANG] = @TEN_NGAN_HANG
      ,[NGUOI_PHU_TRACH] = @NGUOI_PT
      ,[THOI_HAN_BAN_SAO] = @THOI_HAN_BAN_SAO
      ,[BHDS_NGAYHETHAN] = @BHDS_NGAYHETHAN
      ,[BHDS_TEN_CTY_BH] = @BHDS_TEN_CTY_BH
      ,[BHVC_NGAYHETHAN] = @BHVC_NGAYHETHAN
      ,[BHVC_TEN_CTY_BH] = @BHVC_TEN_CTY_BH
      ,[KIEMDINH_TEMXANH] = @KIEMDINH_TEMXANH
      ,[KIEMDINH_TEMVANG] = @KIEMDINH_TEMVANG
      ,[PHI_SD_DUONGBO_NGAY_HETHAN] = @PHI_SD_DB
      ,[SO_THANG_DONG] = @SO_THANG_DONG
      ,[THOIHAN_PHUHIEU_HOPDONG] = @THOIHAN_PHUHIEU_HOPDONG
      ,[GHICHU] = @GHICHU
      ,[BHVC_NOIBO] = @BHVC_NOIBO
      ,[BHVC_BENNGOAI] = @BHVC_BENNGOAI
 WHERE ID = @ID

 SELECT @ID
	END
END
GO

CREATE PROC [VH].[UPDATE_PHUONGTIEN]
@NSX INT,
@SO_KHUNG VARCHAR(50),
@CHU_XE NVARCHAR(200),
@NGAY_NHAP DATE,
@GHICHU_NGAYNHAP NTEXT, 
@NGAY_TL DATE,
@GHICHU_NGAY_TL NTEXT,
@DINHNGHIA_PT_ID INT,
@SO_CHO INT,
@SO_MAY VARCHAR(50),
@DK_LAN_1 DATE,
@SO_DK VARCHAR(50),
@MAU_XE VARCHAR(50),
@ID INT,
@ID_CONGSUAT INT,
@ID_VUNGHOATDONG INT,
@ID_BAIXE INT,
@DIACHI_BAIXE NVARCHAR(200),
@CHIPHI_BAI_XE INT,
@DUNG_TICH_XANG INT
AS
BEGIN
UPDATE [VH].[PHUONGTIEN]
   SET [DINHNGHIA_PT_ID] = @DINHNGHIA_PT_ID 
      ,[DK_LAN_1] = @DK_LAN_1
      ,[SO_KHUNG] = @SO_KHUNG
      ,[SO_MAY] = @SO_MAY
      ,[SO_CHO] = @SO_CHO
      ,[MAU_XE] = @MAU_XE
      ,[ID_CONGSUAT] = @ID_CONGSUAT
      ,[SO_DANGKY] = @SO_DK
      ,[CHU_XE] = @CHU_XE
      ,[ID_VUNGHOATDONG] = @ID_VUNGHOATDONG
      ,[NGAY_NHAP] = @NGAY_NHAP
      ,[GHICHU_NGAY_NHAP] = @GHICHU_NGAYNHAP
      ,[NGAY_THANHLY] = @NGAY_TL
      ,[GHICHU_NGAY_THANHLY] = @GHICHU_NGAY_TL
      ,[BAIXE_ID] = @ID_BAIXE
      ,[DIACHI_BAIXE] = @DIACHI_BAIXE
      ,[CHIPHI_BAIXE] = @CHIPHI_BAI_XE
      ,[IS_DELETED] = 0
      ,[DUNG_TICH_XANG] = @DUNG_TICH_XANG
 WHERE ID = @ID
 SELECT @@ROWCOUNT
 END
GO

CREATE TYPE [VH].[TRANGTHIETBI_TYPE] AS TABLE
(
	ID INT, ID_PHUONGTIEN INT, ID_THIETBI INT, ID_YEUCAU INT, NGAY_CAP DATE, NGAY_HET_HAN DATE, NGAY_GIAO_THEO_XE DATE, TINH_TRANG BIT
)

GO

CREATE PROC [VH].[UPDATE_TRANGTHIETBI]
@tblDATA [VH].[TRANGTHIETBI_TYPE] READONLY
,@VH_ID INT
AS
BEGIN
	DELETE FROM [VH].[TRANGTHIETBI] WHERE ID_PHUONGTIEN = @VH_ID
	INSERT INTO [VH].[TRANGTHIETBI](ID_PHUONGTIEN, ID_THIETBI, ID_YEUCAU, NGAY_CAP, NGAY_HET_HAN, NGAY_GIAO_THEO_XE, TINH_TRANG)
	SELECT ID_PHUONGTIEN, ID_THIETBI, ID_YEUCAU, NGAY_CAP, NGAY_HET_HAN, NGAY_GIAO_THEO_XE, TINH_TRANG FROM @tblDATA
END


